packages:
  - apps/*
  - packages/*

patchedDependencies:
  '@beatzball/litro@0.17.2': patches/@beatzball__litro@0.17.2.patch
  '@beatzball/litro@0.9.1': patches/@beatzball__litro@0.9.1.patch

peerDependencyRules:
  ignoreMissing:
    - vue
